backend:
  name: git-gateway
  branch: main

media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "About Page"
        name: "about"
        file: "content/about.md"
        fields:
          - { name: "title", label: "Title" }
          - { name: "body", label: "Body", widget: "markdown" }
